# Generated by Django 5.0.6 on 2024-06-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_bandanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_collares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_identificadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
    ]
