# Generated by Django 5.0.6 on 2024-06-27 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_canasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='canasta',
            name='bandanas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto_bandanas'),
        ),
        migrations.AddField(
            model_name='canasta',
            name='collares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto_collares'),
        ),
        migrations.AddField(
            model_name='canasta',
            name='identificadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto_identificadores'),
        ),
        
    ]
