# Generated by Django 5.0.6 on 2024-06-27 02:18

from django.db import migrations

def migrate_data(apps, schema_editor):
    # Obtén los modelos
    Canasta = apps.get_model('aplicacion', 'Canasta')
    Producto = apps.get_model('aplicacion', 'Producto')
    Producto_bandanas = apps.get_model('aplicacion', 'Producto_bandanas')
    Producto_collares = apps.get_model('aplicacion', 'Producto_collares')
    Producto_identificadores = apps.get_model('aplicacion', 'Producto_identificadores')
    Producto_ofertas = apps.get_model('aplicacion', 'Producto_ofertas')

    # Transfiere los datos del campo producto a los nuevos campos
    for item in Canasta.objects.all():
        if item.producto:
            if Producto.objects.filter(nombre=item.producto.nombre).exists():
                item.Producto = Producto.objects.get(nombre=item.producto.nombre)
            elif Producto_bandanas.objects.filter(nombre=item.producto.nombre).exists():
                item.Producto_bandanas = Producto_bandanas.objects.get(nombre=item.producto.nombre)
            elif Producto_collares.objects.filter(nombre=item.producto.nombre).exists():
                item.Producto_collares = Producto_collares.objects.get(nombre=item.producto.nombre)
            elif Producto_identificadores.objects.filter(nombre=item.producto.nombre).exists():
                item.Producto_identificadores = Producto_identificadores.objects.get(nombre=item.producto.nombre)
            elif Producto_ofertas.objects.filter(nombre=item.producto.nombre).exists():
                item.Producto_ofertas = Producto_ofertas.objects.get(nombre=item.producto.nombre)
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_canasta_ofertas'),
    ]

    operations = [
    ]
