# Generated by Django 5.0.6 on 2024-06-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20240626_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canasta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto'),
        ),
    ]
